version: '3.8'

services:
  app:
    image: amazoncorretto:17
    ports:
      - "8080:8080"
    volumes:
      - ./target/ShowTime-0.0.1-SNAPSHOT.jar:/app/ShowTime-0.0.1-SNAPSHOT.jar
    command: ["java", "-jar", "/app/ShowTime-0.0.1-SNAPSHOT.jar"]
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://13.233.130.26:5432/countersbd_db
      SPRING_DATASOURCE_USERNAME: countersbd_backend_user
      SPRING_DATASOURCE_PASSWORD: countersbdDb@20240312

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: countersbd_db
      POSTGRES_USER: countersbd_backend_user
      POSTGRES_PASSWORD: countersbdDb@20240312
