services:
  db:
    ports:
      - 5433:5432
      container_name: countersbd_db
      postgres:
        image: postgres:latest
        environment:
          - POSTGRES_DB=countersbd_db
          - POSTGRES_USER=countersbd_backend_user
          - POSTGRES_PASSWORD=countersbdDb@20240312
        volumes:
          - pgdata:/var/lib/postgresql/data
        restart: always
  backend:
    build: .
    container_name: countersbd_backend
    ports:
      - 8080:8080