spring:
  datasource:
    url: jdbc:postgresql://52.66.237.18:5432/db_prod
    username: db_admin
    password: db20240711

sslcommerz:
  store:
    id: countersbd0live
    password: 662A9CCB72A9A14662
  test:
    mode: false
  redirect:
    base:
      url: https://api.countersbd.com
    web:
      url: https://countersbd.com
