spring:
  profiles:
    active: dev

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: releventbangladesh@gmail.com
    password: jufhcvtyaywcwavi
    properties:
      smtp:
        auth: true
        starttls:
          enable: true

server:
  error:
    include-message: always
    include-stacktrace: always

jwt:
  secret: ToolFearInoculumLateralus10000DaysAenemaUndertowAdamJonesMaynardJamesKeananJustinChancellorDaneyCarrey
  exp: 1000000

node:
  id: 012358

cloud:
  aws:
    credentials:
      access-key: AKIA47CRXRGLUQSHYL7J
      secret-key: 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
    region:
        static: ap-south-1
    stack:
      auto: false

application:
  bucket:
    name: countersbd-ticket-bucket
