spring:
  datasource:
    url: jdbc:postgresql://3.109.34.237:5432/countersdb_prod
    username: postgres
    password: Relevant@2024

sslcommerz:
  store:
    id: countersbd0live
    password: 662A9CCB72A9A14662
  test:
    mode: false
  redirect:
    base:
      url: https://api.countersbd.com
    web:
      url: https://countersbd.com