spring:
  datasource:
    url: jdbc:postgresql://showtimedb.c12siig6uo0v.us-east-1.rds.amazonaws.com:5432/showTime
    username: postgres
    password: Tool4421

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

server:
  error:
    include-message: always
    include-stacktrace: always

jwt:
  secret: ToolFearInoculumLateralus10000DaysAenemaUndertowAdamJonesMaynardJamesKeananJustinChancellorDaneyCarrey
  exp: 1000000

node:
  id: 012358