server:
  error:
    include-message: always
    include-stacktrace: always

jwt:
  secret: ToolFearInoculumLateralus10000DaysAenemaUndertowAdamJonesMaynardJamesKeananJustinChancellorDaneyCarrey
  exp: 1000000

node:
  id: 012358

spring:
  profiles:
    active: dev