server:
  error:
    include-message: always
    include-stacktrace: always

jwt:
  secret: ToolFearInoculumLateralus10000DaysAenemaUndertowAdamJonesMaynardJamesKeananJustinChancellorDaneyCarrey
  exp: 1000000

node:
  id: 012358

sslcommerz:
  store:
    id: count65fb2b409c69c
    password: count65fb2b409c69c@ssl
  test:
    mode: true

spring:
  profiles:
    active: dev