spring:
  datasource:
    url: jdbc:postgresql://showtimedb.c12siig6uo0v.us-east-1.rds.amazonaws.com:5432/showTime
    username: postgres
    password: Tool4421

sslcommerz:
  store:
    id: count65fb2b409c69c
    password: count65fb2b409c69c@ssl
  test:
    mode: true
  redirect:
    base:
      url: http://localhost:8080
    web:
      url: http://localhost:3000